name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Publish new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Bump version and Push Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update shared Tag
        run: |
          MAJOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 1)
          MINOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 2)
          git tag -f v$MAJOR
          git tag -f v$MAJOR.$MINOR
          git push -f -u origin v$MAJOR
          git push -f -u origin v$MAJOR.$MINOR

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        if: steps.tag.outputs.release_type == 'major' || steps.tag.outputs.release_type == 'minor'
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
